### ISSUE TITLE
Ubuntu 22.04, the QT window is shown, but no function.

### ISSUE THREAD

**Issue by rudi48** [g4ixt/QtTinySA#19]
Ubuntu 22.04, the QT window is shown, but no function.

Terminal output:

$ sudo ./QtTinySA 
[sudo] password for rudi: 
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
Fontconfig error: Cannot load default config file: No such file: (null)
version = tinySA_v1.4-105-g090fcb8
libGL error: MESA-LOADER: failed to open crocus: /usr/lib/dri/crocus_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: crocus
libGL error: MESA-LOADER: failed to open swrast: /usr/lib/dri/swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: swrast
-----
The Ubuntu Synaptic Package Manager did not found 
the package "crocus".

How can I make it run?
Rudi DL5FA

**Comment by g4ixt** [comment]
Hi Rudi,

To be honest I have few ideas how to help.  You don't need to run it as 'root', so try just 

./QtTinySA

I am running it in Kubuntu 22.04LTS and I have no package called 'crocus',  but I do have various liblg* packages installed, although I did not install them specifically for this.

It might be an issue with your graphics driver, so you could try a Google search for 'libGL error: MESA-LOADER: failed to open swrast:' and see if there are any solutions that sound like they might help.

On my system, the executable doesn't run when it's located on my NAS drive, so I have to put it on a local drive, but the only error I get is 'permission denied' even if I use sudo.

Alternatively you could try installing Python 3.9 and the Python QtTinySA then run it using

Python3 QtTinySA.py

I have recently been able to build a much smaller executable than the one currently on Github, but the updated one won't make any difference I suspect.

**Comment by rudi48** [comment]
Hello Ian,
Thank you for your quick answer.

The "sudo" was needed, because of the access to the serial port.
I know that it could be avoided, but not in detail :-(
Unfortunately I am not so fluent in programming like you ;-)
I will try your reccomendations tomorrow.

**Comment by g4ixt** [comment]
Hello Rudi,

try typing 'groups' in a terminal, this is what I get:
ian adm cdrom sudo dip plugdev lpadmin lxd sambashare

If your user name is not in the plugdev group, I believe that this is needed for the TinySA USB device.  You can add yourself to the group using:
sudo adduser _username_ plugdev

Then you have to log-out and log-in again.  Then try running it without sudo (although I suspect this won't make any difference to your problem).

I have only tested the executable on my system.  I will try it on my Pi which is running Ubuntu Server 22.04LTS

Ian

**Comment by rudi48** [comment]
Hello Ian,
Thank you very much for your good help.

What I did:

Add dialout permission to user rudi:
$ sudo usermod -a -G dialout rudi
# reboot
# check
$ id rudi
uid=1000(rudi) gid=1000(rudi) groups=1000(rudi),4(adm),20(dialout),...
# OK

$ ls -ls /dev/ttyACM3
0 crw-rw---- 1 root dialout 166, 3 Okt 15 11:22 

# start program:
$ ./QtTinySA_0.7.2

# This error is gone now:
"File "serial/serialposix.py", line 325, in open
serial.serialutil.SerialException: [Errno 13] could not open port /dev/ttyACM3: [Errno 13] Permission denied:"

Sorry Ian, it is too complicated for me (age 75), now I give up.

**Comment by g4ixt** [comment]
I am sorry that I couldn't be of more help.

Ian
