### ISSUE TITLE
personalized configuration files

### ISSUE THREAD

**Issue by winnieXY** [g4ixt/QtTinySA#32]
To publish QtTinySA we need to work within a multi-user environment. In order to do so I've prepared a small patch (extension of class database) to create a localized database.

There is just a little work needed for darwin and windows systems to determine the correct paths where to install a global configuration file and where to install a personalized one. 

I wrote the patch in a way that if there is no global configuration file and no personalized one QtTinySA will fallback to the old behaviour (looking into the current folder) . As I've no pyinstaller I can't test the resulting binary but it should work in eyes.

**Comment by winnieXY** [comment]
[personalized_database.txt](https://github.com/g4ixt/QtTinySA/files/14213611/personalized_database.txt)

**Comment by g4ixt** [comment]
completed
