### ISSUE TITLE
preset bands and marker import failing

### ISSUE THREAD

**Issue by simonTx1** [g4ixt/QtTinySA#37]
Hi, 
I just tried using the new marker import feature from the QtTinySA.exe V0.10.0  . It seems like there is a few issues : 

- pressing "Add Row" does not seem to add any row in the table display above it.
- importing a "RF mic" formatted csv doesn't add any row, but does not print error message in the command prompt either.

- exporting a marker list from QtTinySA ("broadcast" list), then importing this same list returns :  "IndexError: list index out of range"
- exporting a marker list from QtTinySA ("broadcast" list), changing the "StartF" value then trying to import returns : "ValueError: could not convert string to float: 'True'" 
--> QtTinySA.py  line 866 : misalignment in between the row[index[...]] and the expected arguments ? 

Simon

**Comment by g4ixt** [comment]
Oh dear that's a long list.

'Add Row' should add a row underneath the one clicked.  It's not committed to the database until you click out of the row, then it should be sorted in ascending frequency order.

Yes, importing is not working.  I must have broken if somehow after I tested it - I will look and fix it.  Sorry about that.

Ian

**Comment by g4ixt** [comment]
Hopefully all now fixed in v0.10.1

**Comment by g4ixt** [comment]
You MUST replace the database in your "personal" folder with the new one included in the 0.10.1 release
