### ISSUE TITLE
Configuration file QtTSAprefs.db

### ISSUE THREAD

**Issue by ghmon** [g4ixt/QtTinySA#43]
After starting the program for the very first time, a FILE (not a directory!) ~/.config/QtTinySA is created, and therefore exceptions occur. Creating a DIRECTORY ~/.local/QtTinySA before the very first start and everything is ok, QtTSAprefs.db is created within that directory.

python 3.10.12. Ubuntu 22.04 LTS. Did not use a venv.

**Comment by g4ixt** [comment]
I suspect that the problem here, and with issue #43, is that your 'platformdirs' python package is old. It doesn't seem to have been updated in the repository since 2022.

**Comment by ghmon** [comment]
Yes, that was the problem. After updating to platformdirs 4.2.0 it worked, deleted ~/.config/QtTinySA/ beforehand and started the program.
