### ISSUE TITLE
class database, __init__, ensure_exists=True not known attribute

### ISSUE THREAD

**Issue by ghmon** [g4ixt/QtTinySA#45]
TypeError: user_config_dir() got an unexpected keyword argument 'ensure_exists'

I simply deleted the ensure_exists part. Worked.

python 3.10.12. Ubuntu 22.04 LTS. Did not use a venv.

**Comment by g4ixt** [comment]
I suspect that the problem here, and with issue #44, is that your 'platformdirs' python package is old.  It doesn't seem to have been updated in the repository since 2022.

**Comment by g4ixt** [comment]
I will look at changing the code to avoid this issue.

**Comment by ghmon** [comment]
> I will look at changing the code to avoid this issue.

Thanks!

Yes, that was the problem. After updating to platformdirs 4.2.0 it worked, deleted ~/.config/QtTinySA/ beforehand and started the program.
