### ISSUE TITLE
10 vertical gridlines as standard

### ISSUE THREAD

**Issue by elraval** [g4ixt/QtTinySA#46]
Hi. 

Would it be possible to mantain 10 vertical gridlines?. The number of lines seem to change depending on the span now, and 10 gridlines is pretty standard in spectrum analysers.

Thank you in advance. Cheers,

D

**Comment by elraval** [comment]
10 gridlines allow for easy channel identifucation withing a given span. My main use case is wireless microphone frequency coordination and band planning. My typical Span ranges when monitoring frequencies are multiples of 8MHz (which is the bandwidth of one TV channel in Europe). For instance, 80MHz span would make 10 channels visible with a gridline separating each one of them.

I made a similar request https://groups.io/g/tinysa/message/10744 to Erik while ago and he built firmware revision on tinySA to accomodate this: https://groups.io/g/tinysa/topic/97840732#11011

Hope you find this topics helpful in understanding the advantages. Cheers

**Comment by CliveTombs** [comment]
It is my belief that the old 10 (or what ever number) graticule divisions has had its day. It was born out of the requirement for something to subdivide a screen and had to be etched into the perspex screen. 
However now we can have the flexibility to have the marking stay on a particular integer MHz boundry. But to accommodate any speific requirement of a 'not on a whole MHz' boundry we have the 'Preset bands and Markers' function within the preference tab.  Attached is a screenshot where I have marked the channels in use at a Radio transmitter station. 
In the mic use case TV channel boundries could be added as markers. The advantage over simple 10 graticules is that as one spans in or out, the marker will stay true to the frequency required not some arbitary location across the screen.
![Screenshot_20240413_114918](https://github.com/g4ixt/QtTinySA/assets/15659511/4153ddc1-d25e-4041-90ea-181e5b312569)

**Comment by g4ixt** [comment]
[TV_channels.csv](https://github.com/g4ixt/QtTinySA/files/14967250/TV_channels.csv)

![tv_channels](https://github.com/g4ixt/QtTinySA/assets/76836635/0c481924-696b-409f-9378-0425945128cd)
