### ISSUE TITLE
Raspberry Pi 5, Debian GNU/Linux 12 (bookworm) aarch64: hack to run QtTinySA-0.10.3

### ISSUE THREAD

**Issue by llamatrails** [g4ixt/QtTinySA#53]
Raspberry Pi 5, 64bit
  OS: Debian GNU/Linux 12 (bookworm) aarch64
   /etc/issue:  Debian GNU/Linux 12
   /etc/debian_version: 12.5
QtTinySA-0.10.3

I tried to follow your Wiki page on the Pi OS 12, but couldn't get either of your suggestions to work.

I'm no python programmer, but I have gotten QtTinySA-0.10.3 to run.  Maybe it will help?
First I loaded all the required packages.
Then ...

**** first try
rick@raspi5:/home/rick/Downloads/QtTinySA-0.10.3$ python3 QtTinySA.py
python3 QtTinySA.py QStandardPaths: wrong permissions on runtime directory /run/user/1000, 0770 instead of 0700

**** make sure /run/user/1000 is set to 700.
**** Not sure how it got changed, my other Pi with Debian Bookworm is at 700, no attempt to run QtTinySA on it yet.

**** second try
rick@raspi5:/home/rick/Downloads/QtTinySA-0.10.3$ python3 QtTinySA.py
Traceback (most recent call last):
  File "/home/rick/Downloads/QtTinySA-0.10.3/QtTinySA.py", line 1143, in <module>
    config = database()
             ^^^^^^^^^^
  File "/home/rick/Downloads/QtTinySA-0.10.3/QtTinySA.py", line 731, in __init__
    self.personalDir = platformdirs.user_config_dir(appname=app.applicationName(), ensure_exists=True)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: user_config_dir() got an unexpected keyword argument 'ensure_exists'
rick@raspi5:/home/rick/Downloads/QtTinySA-0.10.3$

**** kuldge around the above:
	edit QtTinySA.py line 731 to remove the: ensure_exists=True
	if ~/.config/QtTinySA is now a file, delete it
	create ~/.config/QtTinySA as a directory

**** it works !!!
rick@raspi5:/home/rick/Downloads/QtTinySA-0.10.3$ python3 QtTinySA.py

**Comment by g4ixt** [comment]
The 'ensure exists' issue is most likely because your version of 'platformdirs' is old.

Ian

**Comment by llamatrails** [comment]
Not doubting that, but I couldn't get your suggestions on the wiki to work, so hack away I went.

Appreciate your program, happy to have found it,
Rick
