### ISSUE TITLE
Cannot sample about 6ghz

### ISSUE THREAD

**Issue by ashjmckenzie** [g4ixt/QtTinySA#59]
I'm on v0.10.6 i cannot run sweeps above 6ghz it just stops drawing, also cannot enter values above 6000mhz in any field (Center, Start, End)

**Comment by g4ixt** [comment]
This is because the TinySA-Ultra [specification](https://tinysa.org/wiki/pmwiki.php?n=TinySA4.Specification) frequency range is up to 6GHz.  Whilst it is possible to use the hardware above this frequency it's not calibrated so it seemed a reasonable limitation to impose.

**Comment by ashjmckenzie** [comment]
Would it be possible for you to extend this to 12ghz? , while not
calibrated, there are a number of applications tiny is useful for in this
space, including video links and satellite downlinks, tiny can observe up
to 12g

Many thanks

**Comment by g4ixt** [comment]
It's certainly possible, the limit is set on Line 88

**Comment by g4ixt** [comment]
It's certainly possible, the limit is set on Line 88 and you can change it yourself.
self.maxF = 6000

Changing it might introduce bugs somewhere so you would need to test it.  I added an "external mixer/LNB" mode for use with satellite downlinks and you will almost certainly get better results like signal/noise at 12GHz by using that with suitable hardware.

I don't intend to modify the code so if you make the change and then update to a later version you will need to change it again.  If it introduces any bugs, let me know.

**Comment by g4ixt** [comment]
I have added the max frequency to the 'preferences' screen and it is stored in the configuration database.  This will be in the next version.  It only takes effect after closing and re-opening the programme.

**Comment by ashjmckenzie** [comment]
Thank you !

**Comment by burgerwdev** [comment]
I've tried to set the max operating frequency to 12000Mhz and 20000Mhz, and Quit/Restart the app, but it didn't work, I still can't change the Start/Center/Stop frequency over 6Ghz.
I am using latest QtTinySA v1.2.2 on Mac Air M1.

**Comment by g4ixt** [comment]
fixed in v 1.2.5 although I have not yet managed to compile any executables
