### ISSUE TITLE
GUI does not respond in Ubuntu 22.04

### ISSUE THREAD

**Issue by KedalionDaimon** [g4ixt/QtTinySA#62]
I got the dependencies, fired it up, no error message, but then, I could not "click" (so as to receive any change, feedback or effect) on any menu option. You click anywhere, NOTHING happens. Then, Ubuntu told me the application does not react and whether I want to kill it. Also, it did not maximize properly, just changed position and produced artefacts. This is Ubuntu 22.04 with X11. Please be so kind and have a look into it, when you get the time.

**Comment by g4ixt** [comment]
I can't think of much to suggest.  It normally works fine on 22.04.  You could try the Linux executable, it's built on 22.04.

It's a Qt application so you could Google the symptoms for that.

Please share the messages shown in the terminal screen.

Anyone got any ideas?

Ian

**Comment by g4ixt** [comment]
No response
