### ISSUE TITLE
QtTinySA linux executable does not run in Debian stable (bookworm)

### ISSUE THREAD

**Issue by ugaiser** [g4ixt/QtTinySA#64]
QtTinySA linux executable does not run in Debian stable (bookworm, 12.7):

Traceback (most recent call last):
  File "QtTinySA.py", line 27, in <module>
ImportError: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by /tmp/_MEIDTQOLD/libX11.so.6)
[194103] Failed to execute script 'QtTinySA' due to unhandled exception! 

Debian stable uses glibc v2.36
I suspect that older Ubuntu versions have the same problem. Ubuntu 22.04 LTS ("jammy") uses glibc 2.35

73,
Uli  DF7SC

**Comment by g4ixt** [comment]
Uli,

Thank you for the information.  The executable was built on my desktop PC that I updated to Kubuntu 24.04.01-LTS last week when it was released.  It and my laptop on Lubuntu 24.04 have glibc 2.38-1 and my Pi4 'bookworm' has glibc 2.36-1.  I am surprised that it didn't include the library in the executable, I thought that was the reason to do it but I am no expert.

I would like to keep compatibility with Ubuntu 22.04.  I will look to see if I can use Github 'actions' to compile one, or I will ask my friend Clive if he has a machine he can build one on.

Ian

**Comment by g4ixt** [comment]
Uli,

Could you try the QtTinySA.bin executable in the v0.11.8 release [here](https://github.com/g4ixt/QtTinySA/releases/tag/v0.11.8) please and let me know if it works on 22.04?

**Comment by ugaiser** [comment]
Ian,

I don't have Ubuntu 22.04 here, so I couldn't test with it.
QtTinySA.bin v0.11.8 now works in Debian stable (v12, "bookworm") and in Debian testing (future v13, "trixie").
It does not work in Debian oldstable (v11, "bullseye") and not in Ubuntu 20.04 LTS.

Thank you very much 
Uli

**Comment by g4ixt** [comment]
Uli,

Thank you, that is a success then and good to know about the others.

Ian
